(()=>{
'use strict';
const TOTAL=10,$=id=>document.getElementById(id),grid=$('ballGrid'),court=$('court'),shotBall=$('shotBall'),hoopTarget=$('hoopTarget'),rimVisual=$('rimVisual'),netVisual=$('netVisual'),message=$('message'),roundNo=$('roundNo'),shotsNo=$('shotsNo'),winsNo=$('winsNo'),musicBtn=$('musicBtn'),soundBtn=$('soundBtn'),resetBtn=$('resetBtn'),confetti=$('confetti');
let buttons=[],used=new Set(),round=1,wins=0,winner=0,lastWinner=0,locked=false,musicOn=true,sfxOn=true,audioCtx=null,musicTimer=null,musicStep=0;
const rand=n=>Math.floor(Math.random()*n);
function chooseWinner(){let n;do{n=rand(TOTAL)+1}while(n===lastWinner);lastWinner=n;return n}
function hud(){roundNo.textContent=round;shotsNo.textContent=used.size;winsNo.textContent=wins}
function setMessage(text,sub,type=''){message.className='message'+(type?' '+type:'');message.innerHTML=`${text}<span class="sub">${sub}</span>`}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function startMusic(){if(musicTimer)return;ensureAudio();const bass=[98,98,110,98,82,98,110,123],lead=[392,440,392,349,392,440,494,440];musicTimer=setInterval(()=>{if(!musicOn||!audioCtx)return;const t=audioCtx.currentTime,i=musicStep%8,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=bass[i];g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.022,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.28);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+.3);if(i%2===0){const l=audioCtx.createOscillator(),lg=audioCtx.createGain();l.type='square';l.frequency.value=lead[i];lg.gain.setValueAtTime(.0001,t);lg.gain.exponentialRampToValueAtTime(.008,t+.01);lg.gain.exponentialRampToValueAtTime(.0001,t+.16);l.connect(lg).connect(audioCtx.destination);l.start(t);l.stop(t+.18)}musicStep++},390)}
function wakeAudio(){ensureAudio();if(musicOn)startMusic()}
function tone(freq,dur=.1,type='sine',vol=.025,delay=0){if(!sfxOn)return;ensureAudio();const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+dur+.03)}
function noise(dur=.1,vol=.025,hp=900){if(!sfxOn)return;ensureAudio();const b=audioCtx.createBuffer(1,Math.floor(audioCtx.sampleRate*dur),audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=audioCtx.createBufferSource(),f=audioCtx.createBiquadFilter(),g=audioCtx.createGain();s.buffer=b;f.type='highpass';f.frequency.value=hp;g.gain.value=vol;s.connect(f).connect(g).connect(audioCtx.destination);s.start()}
function bounceSfx(){tone(125,.08,'triangle',.035);tone(92,.11,'triangle',.025,.04)}function whoosh(){noise(.16,.026,700)}function rimSfx(){tone(820,.055,'square',.026);tone(570,.12,'triangle',.02,.025)}function missSfx(){tone(175,.14,'triangle',.024)}function swish(){noise(.13,.028,1600);tone(550,.08,'triangle',.024,.02);tone(780,.13,'sine',.018,.08)}function crowd(){tone(392,.12,'sawtooth',.016);tone(494,.12,'sawtooth',.014,.05);tone(659,.16,'sawtooth',.014,.11)}
function makeBalls(){grid.innerHTML='';buttons=[];for(let i=1;i<=TOTAL;i++){const b=document.createElement('button');b.className='ball-btn';b.setAttribute('aria-label',`Basketball ${i}`);b.innerHTML=`<div class="basketball"><span class="arc l"></span><span class="arc r"></span><span class="ball-number">${i}</span></div><span class="ball-label">Ball ${i}</span>`;b.addEventListener('click',()=>shoot(i,b));grid.appendChild(b);buttons.push(b)}}
function setAvailable(){buttons.forEach((b,i)=>{const n=i+1;b.disabled=used.has(n);b.classList.toggle('used',used.has(n))})}
function P(x,y){return{x:court.clientWidth*x,y:court.clientHeight*y}}
function bez(a,b,c,t){const u=1-t;return{x:u*u*a.x+2*u*t*b.x+t*t*c.x,y:u*u*a.y+2*u*t*b.y+t*t*c.y}}
function place(p,scale=1,rot=0){shotBall.style.opacity='1';shotBall.style.transform=`translate3d(${p.x}px,${p.y}px,0) scale(${scale}) rotate(${rot}deg)`}
function hide(){shotBall.style.opacity='0'}
function animate(ms,draw,done){const start=performance.now();function frame(now){const t=Math.min((now-start)/ms,1);draw(t);if(t<1)requestAnimationFrame(frame);else if(done)done()}requestAnimationFrame(frame)}
function flashRim(){hoopTarget.classList.remove('hit');void hoopTarget.offsetWidth;hoopTarget.classList.add('hit')}
function rimPoint(){const c=court.getBoundingClientRect(),r=rimVisual.getBoundingClientRect(),half=shotBall.offsetWidth/2;return{x:r.left-c.left+r.width/2-half,y:r.top-c.top+r.height/2-half}}
function makeAnimation(done){const a=P(.05,.78),c=P(.31,.05),rim=rimPoint(),drop={x:rim.x,y:rim.y+125};bounceSfx();setTimeout(whoosh,200);animate(2250,t=>place(bez(a,c,rim,t),1-.2*t,820*t),()=>{swish();netVisual.classList.add('swish');animate(560,t=>place({x:rim.x,y:rim.y+(drop.y-rim.y)*t},.8-.23*t,820+260*t),()=>{hide();setTimeout(()=>netVisual.classList.remove('swish'),180);done()})})}
function missAnimation(done){const a=P(.05,.78),c=P(.31,.06),rim=rimPoint(),right=Math.random()>.5,end=right?P(.93,.58):P(.53,.55),ctrl=right?P(.94,.20):P(.66,.20);bounceSfx();setTimeout(whoosh,200);animate(2250,t=>place(bez(a,c,rim,t),1-.18*t,800*t),()=>{flashRim();rimSfx();animate(950,t=>place(bez(rim,ctrl,end,t),.82+.04*Math.sin(Math.PI*t),800+(right?560:-480)*t),()=>{missSfx();hide();done()})})}
function confettiBurst(){confetti.innerHTML='';const colors=['#ffd66d','#70ddff','#68eba8','#ff8499','#fff','#ff9c47'];for(let i=0;i<36;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.background=colors[i%colors.length];p.style.setProperty('--dx',(Math.random()*260-130)+'px');p.style.animationDuration=(1.5+Math.random())+'s';confetti.appendChild(p)}setTimeout(()=>confetti.innerHTML='',2200)}
function newRound(){used.clear();locked=false;winner=chooseWinner();buttons.forEach(b=>{b.disabled=false;b.className='ball-btn'});hide();hud();setMessage('New round ready','Ask the next question, then let a student choose a number.')}
function shoot(num,btn){if(locked||used.has(num))return;wakeAudio();used.add(num);locked=true;buttons.forEach(b=>b.disabled=true);btn.classList.add('used');hud();const isWin=num===winner;setMessage(`Ball ${num} is in the air...`,isWin?'That one looks good!':'Watch the rim...');const finish=()=>{if(isWin){wins++;btn.classList.remove('used');btn.classList.add('win');crowd();confettiBurst();hud();setMessage(`SWISH! Ball ${num} scores!`,'New round starting with a different winning number.','made');setTimeout(()=>{round++;newRound()},2200)}else{locked=false;setAvailable();setMessage(`Miss! Ball ${num} hit the rim and bounced away.`,'Keep answering questions and try another number.','miss')}};isWin?makeAnimation(finish):missAnimation(finish)}
musicBtn.addEventListener('click',()=>{ensureAudio();musicOn=!musicOn;if(musicOn)startMusic();musicBtn.textContent=musicOn?'♫ Music: On':'♫ Music: Off'});soundBtn.addEventListener('click',()=>{ensureAudio();sfxOn=!sfxOn;soundBtn.textContent=sfxOn?'🔊 SFX: On':'🔇 SFX: Off'});resetBtn.addEventListener('click',()=>{wakeAudio();round=1;wins=0;lastWinner=0;newRound()});
makeBalls();winner=chooseWinner();hud();
})();
